### ISSUE TITLE
Create an thread here to make a server suggestion

### ISSUE THREAD

**Issue by gmanc2** [gmanc2/EclipseRP#1]
Do you have something you want to be added to the server?

Let me know by posting it here and I'll add it to the project [board](https://github.com/gmanc2/EclipseRP/projects).

**Comment by ArWilson52101** [comment]
forgot to blacklist some props heres a list
models/props_canal/rock_riverbed01c.mdl
models/props_phx/trains/monorail_curve.mdl
models/props_phx/trains/monorail_curve2.mdl
models/hunter/blocks/cube6x8x05.mdl
models/props_phx/huge/road_short.mdl
models/props_phx/huge/road_medium.mdl
models/props_phx/huge/road_long.mdl
models/props_phx/huge/road_curve.mdl
models/props_phx/playfield.mdl

**Comment by Empiur** [comment]
You should add third person view to the server.
